src/kochilatt/kochilatt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patient/', include('patient.urls'))
]

src/kochilatt/patient/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PatientList.as_view(), name='index'),
    path('create/', views.PatientCreate.as_view(), name='create'),
    path('update/<int:pk>', views.PatientUpdate.as_view(), name='update'),
    path('delete/<int:pk>', views.PatientDelete.as_view(), name='delete'),
    path('<int:pk>/', views.PatientDetail.as_view(), name='detail'),

]

src/kochilatt/patient/models.py
from django.db import models

class Patient(models.Model):

    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = ("patient")
        verbose_name_plural = ("patients")

    def __str__(self):
        return self.name
    

src/kochilatt/patient/views.py
from django.shortcuts import render
from django.urls import reverse_lazy  
from django.views import generic  
from .models import Patient


class PatientList(generic.ListView):
    model = Patient
    template_name = "patient/index.html"

class PatientCreate(generic.CreateView):
    model = Patient
    fields = ['name']
    success_url = reverse_lazy('index')

class PatientUpdate(generic.UpdateView):
    model = Patient
    fields = ['name']
    success_url = reverse_lazy('index')

class PatientDelete(generic.DeleteView):
    model = Patient
    success_url = reverse_lazy('index')

class PatientDetail(generic.DetailView):
    model = Patient

src/kochilatt/patient/templates/patient/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <title>Patients</title>
</head>
<body>

    <div class="p-5"></div>
    <div class="container">
        <div class="row">
            <div class="offset-4 col-4">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between">
                            <b>Patients</b>
                            <a href="{% url 'create' %}">add</a>
                        </div>
                    </div>
                    <ul class="list-group list-group-flush">
                    {% for patient in patient_list %}
                        <li class="list-group-item d-flex justify-content-between">
                            <div>
                                <a href="{% url 'detail' patient.pk %}">{{ patient.name }}</a>
                            </div>
                            <div>
                                <a href="{% url 'update' patient.pk %}">Edit</a>
                                &nbsp;
                                <a href="{% url 'delete' patient.pk %}">Delete</a>
                            </div>
                        </li>
                    {% empty %}
                        <p class="text-center p-5">no patient yet....</p>
                    {% endfor %}
                    </ul>
                
                </div>
            </div>
        </div>
    </div>


    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

src/kochilatt/patient/templates/patient/patient_confirm_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>delete</title>
</head>

<body>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ patient.name }}"?</p>
        <input type="submit" value="Confirm">
    </form>
</body>

</html>

src/kochilatt/patient/templates/patient/patient_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>{{ patient.name }}</h1>
</body>
</html>

src/kochilatt/patient/templates/patient/patient_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h4>Add a new patient</h4>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save">
    </form>
</body>
</html>